import Navbar from '@/components/layout/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Montserrat } from 'next/font/google'
import Sidebar from '@/components/layout/Sidebar'

const montserrat = Montserrat({ weight: "600", subsets: ['latin'] })



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='dark'>

        <div>
          <Navbar />
        </div>
        <div className=' flex '>
          <div className='hidden md:flex'>
            <Sidebar />
          </div>
          <div className='w-full'>
            {children}
          </div>
        </div>

      </body>
    </html>
  )
}
